version: 2.1

orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - codecov/upload:
          file: ./coverage/lcov.info

  release:
    docker:
      - image: 'circleci/node:latest'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm rebuild node-sass
            - run: npm run build:cjs
            - run: npm run build:umd
            - run:
                name: Copy files and relesae
                command: |
                  cp package.json README.md LICENSE ./build
                  cd ./build
                  mv node_modules external
                  find . -type f | xargs sed -i  's/node_modules/external/g'
                  npm run release

workflows:
    build-and-test:
      jobs:
        - lint
        - test
        - release:
            requires:
              - lint
              - test