version: 2.1

orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - store_artifacts:
          path: ./coverage/lcov.info
      - codecov/upload:
          file: ./coverage/lcov.info

workflows:
    build-and-test:
      jobs:
        - lint
        - test